
[package]
name = "bevy_sly_compute_macros"
version = "0.0.1"
edition = "2021"
description = "Derive implementations for orbit"

[lib]
proc-macro = true

[dependencies]
bevy_macro_utils = { version = "0.12" }

syn = "2.0"
proc-macro2 = "1.0"
quote = "1.0"
